# ayarlar.py
# ---------------------------------------------------------
# Laboratuvar Envanter Sistemi - Yapılandırma ve Dil Dosyası
# ---------------------------------------------------------

metinler = {
    "TR": {
        "title": "Laboratuvar Envanter Sistemi",
        "logo": "Lab Envanter",
        "envanter": "📦  Envanter",
        "yeni_ekle": "➕  Yeni Ekle",
        "gecmis": "🕒  Geçmiş",
        "yedekleme": "💾  Yedekleme",
        "tema_degistir": "🌓  Tema Değiştir",
        "dil_sec": "🌐  TR / EN",
        "kullanici_degistir": "👤 Kullanıcı Değiştir",
        "malzeme_adi": "Malzeme Adı:",
        "lokasyon": "Lokasyon (Raf/Oda):",
        "notlar": "Özel Notlar:",
        "kaydet": "💾 Kaydet",
        "guncelle": "Güncelle",
        "sil": "Sil",
        "arama": "🔍 Malzeme ara...",
        "disa_aktar": "📊 Excel'e Aktar",
        "gecmisi_disa_aktar": "📊 Geçmişi Excel'e Aktar",
        "toplam": "Toplam Çeşit: ",
        "emin_misin_kullanici": "'{}' kullanıcısını silmek istediğinize emin misiniz?",
        "emin_misin_malzeme": "Bu malzemeyi kalıcı olarak silmek istediğinize emin misiniz?",
        "evet": "Evet, Onaylıyorum",
        "hayir": "İptal",
        "ana_miktar": "1. Ana Miktar:",
        "ek_miktar_2": "2. Ek Miktar:",
        "ek_miktar_3": "3. Ek Miktar:",
        "miktar_zorunlu": "Miktar (Zorunlu)",
        "opsiyonel": "Opsiyonel",
        "db_islemleri": "Veritabanı (.db) İşlemleri",
        "db_aciklama": "Sistemin kopyasını bilgisayara kaydeder veya geri yükler.",
        "db_yedekle_btn": "💾 Veritabanını Yedekle",
        "db_kurtar_btn": "📂 Veritabanını Kurtar",
        "csv_islemleri": "Excel (.csv) İçeri Aktarma",
        "csv_aciklama": "Daha önce Excel'e aktardığınız '.csv' dosyasını sisteme yükler.",
        "csv_yukle_btn": "📥 Excel'den Yükle",
        "yukleniyor": "Yükleniyor...",
        "bulunamadi": "Eşleşen malzeme bulunamadı.",
        "yeni_deger_kaydet": "💾 Yeni Değerleri Kaydet",
        "sayilan_miktarlar": "Laboratuvarda Sayılan Miktarlar:",
        "lokasyon_guncelle": "Lokasyon (Konum):",
        "islem_yok": "Henüz hiç işlem yapılmamış.",
        "kim_giris": "Kim Giriş Yapıyor?",
        "yeni_kullanici": "Yeni Kullanıcı Ekle:",
        "ekle_btn": "Ekle",
        "kayitli_yok": "Kayıtlı kullanıcı yok.",
        "isim_girin": "İsim girin...",
        "orn_isim": "Örn: Sodyum Klorür",
        "orn_lok": "Örn: A Dolabı, Raf 2",
        "birimler": ["Koli", "Paket", "Kutu", "Şişe", "Adet", "ml", "L", "g", "mg", ""],
        "log_eklendi": "Sisteme Eklendi",
        "log_silindi": "Kalıcı Olarak Silindi",
        "log_guncellendi": "Bilgiler Güncellendi",
        "log_miktar": "Miktar",
        "log_stok": "Son Stok"
    },
    "EN": {
        "title": "Laboratory Inventory System",
        "logo": "Lab Inventory",
        "envanter": "📦  Inventory",
        "yeni_ekle": "➕  Add New",
        "gecmis": "🕒  History",
        "yedekleme": "💾  Backup",
        "tema_degistir": "🌓  Toggle Theme",
        "dil_sec": "🌐  EN / TR",
        "kullanici_degistir": "👤 Switch User",
        "malzeme_adi": "Material Name:",
        "lokasyon": "Location (Shelf/Room):",
        "notlar": "Special Notes:",
        "kaydet": "💾 Save",
        "guncelle": "Update",
        "sil": "Delete",
        "arama": "🔍 Search items...",
        "disa_aktar": "📊 Export to Excel",
        "gecmisi_disa_aktar": "📊 Export History",
        "toplam": "Total Items: ",
        "emin_misin_kullanici": "Are you sure you want to delete user '{}'?",
        "emin_misin_malzeme": "Are you sure you want to permanently delete this item?",
        "evet": "Yes, Confirm",
        "hayir": "Cancel",
        "ana_miktar": "1. Main Qty:",
        "ek_miktar_2": "2. Extra Qty:",
        "ek_miktar_3": "3. Extra Qty:",
        "miktar_zorunlu": "Amount (Req)",
        "opsiyonel": "Optional",
        "db_islemleri": "Database (.db) Operations",
        "db_aciklama": "Saves a full copy of the system to your PC or restores it.",
        "db_yedekle_btn": "💾 Backup Database",
        "db_kurtar_btn": "📂 Restore Database",
        "csv_islemleri": "Excel (.csv) Import",
        "csv_aciklama": "Imports a previously exported '.csv' file into the system.",
        "csv_yukle_btn": "📥 Import from Excel",
        "yukleniyor": "Loading...",
        "bulunamadi": "No matching items found.",
        "yeni_deger_kaydet": "💾 Save New Values",
        "sayilan_miktarlar": "Quantities Counted in Lab:",
        "lokasyon_guncelle": "Location (Position):",
        "islem_yok": "No operations performed yet.",
        "kim_giris": "Who is Logging In?",
        "yeni_kullanici": "Add New User:",
        "ekle_btn": "Add",
        "kayitli_yok": "No registered users.",
        "isim_girin": "Enter name...",
        "orn_isim": "Ex: Sodium Chloride",
        "orn_lok": "Ex: Cabinet A, Shelf 2",
        "birimler": ["Case", "Package", "Box", "Bottle", "Piece", "ml", "L", "g", "mg", ""],
        "log_eklendi": "Added to System",
        "log_silindi": "Permanently Deleted",
        "log_guncellendi": "Information Updated",
        "log_miktar": "Quantity",
        "log_stok": "Last Stock"
    }
}

font_tipi = "Segoe UI"

renkler = {
    "arkaplan": ("#F0F4F8", "#13151A"),          
    "menu": ("#FFFFFF", "#1E2028"),               
    "kart": ("#FFFFFF", "#272A35"),               
    "yazi_ana": ("#111827", "#F9FAFB"),           
    "yazi_ikincil": ("#6B7280", "#9CA3AF"),       
    "buton_mavi": ("#3B82F6", "#3B82F6"),         
    "buton_mavi_hover": ("#2563EB", "#2563EB"),   
    "basari": ("#10B981", "#10B981"),             
    "tehlike": ("#EF4444", "#EF4444"),            
    "uyari": ("#F59E0B", "#F59E0B")               
}